language: scala
scala:
   - 2.12.2
jdk:
  - oraclejdk8

before_script:
  - "npm install -g jshint"
  - "npm install jsdom@9.12.0"

script:
  - sbt test
  - sbt scalastyle
  - sbt test:scalastyle # run scalastyle in test code
  - jshint app/jvm/src/main/assets/javascripts
