language: scala
scala:
   - 2.11.6
jdk:
  - oraclejdk8

before_script:
  - "npm install -g jshint"

script:
  - sbt test
  - sbt scalastyle
  - sbt test:scalastyle # run scalastyle in test code
  - jshint app/jvm/src/main/assets/javascripts
