!!models.accounting.config.Parsable$Config
categories:
  - &catLife
      code: LIFE
      name: "Groceries"
      helpText: "Food, Toothpaste, .."
  - &catFun
      code: FUN
      name: "Fun"
      helpText: "Pub, Ice cream, .."
  - &catRecur
      code: RECUR
      name: "Recurring"
      helpText: "Monthly/yearly/.. recurring expenses"
  - &catOne
      code: ONE
      name: "One-time"
      helpText: "Furniture, electronics, .."
  - &catPres
      code: PRES
      name: "Gifts"
      helpText: ""
  - &catCloth
      code: CLOTH
      name: "Clothing"
      helpText: ""
  - &catMed
      code: MED
      name: "Medical"
      helpText: ""
  - &catTrans
      code: TRANS
      name: "Transportation"
      helpText: ""
  - &catFinan
      code: FINAN
      name: "Financial"
      helpText: "Interest, bank charges, .."
  - &catIn
      code: IN
      name: "Income"
      helpText: "wages, .."
  - &catTax
      code: TAX
      name: "Taxes"
      helpText: ""
  - &catAcc
      code: ACC
      name: "Accounting"
      helpText: "Non-real flows of money"
  - &catEndow
      code: ENDOW
      name: "Endowments"
      helpText: "Common account refill"
  - &catBig
      code: BIG
      name: "Big"
      helpText: "E.g. buying a house"
  - &catInvest
      code: INVEST
      name: "Investments"
      helpText: "E.g. shares"

accounts:
  - &accountCommon
      code: Common
      longName: Common
      shorterName: Common
      veryShortName: C.
      defaultElectronicReservoirCode: CARD_COMMON
      categories:
        - *catLife
        - *catFun
        - *catTrans
        - *catCloth
        - *catRecur
        - *catOne
        - *catPres
        - *catMed
        - *catFinan
        - *catEndow
        - *catAcc
      summaryTotalRows:
        - rowTitleHtml: <b>Total</b>
          categoriesToIgnore: [*catAcc]
        - rowTitleHtml: <b>Total</b> <small>(without endow.)</small>
          categoriesToIgnore: [*catAcc, *catEndow]

  - &accountAlice
      code: Alice
      longName: Alice
      shorterName: Alice
      veryShortName: A.
      userLoginName: alice
      defaultCashReservoirCode: CASH_ALICE
      defaultElectronicReservoirCode: CARD_ALICE
      categories:
        - *catFun
        - *catLife
        - *catTrans
        - *catCloth
        - *catRecur
        - *catOne
        - *catPres
        - *catMed
        - *catIn
        - *catFinan
        - *catTax
        - *catEndow
        - *catBig
        - *catInvest
        - *catAcc
      summaryTotalRows:
        - rowTitleHtml: <b>Total</b>
          categoriesToIgnore: [*catAcc]
        - rowTitleHtml: <b>Total</b> <small>(without invest.)</small>
          categoriesToIgnore: [*catAcc, *catInvest]
  - &accountBob
      code: Bob
      longName: Bob
      shorterName: Bob
      veryShortName: B.
      userLoginName: bob
      defaultCashReservoirCode: CASH_COMMON
      defaultElectronicReservoirCode: CARD_BOB
      categories:
        - *catFun
        - *catTrans
        - *catCloth
        - *catRecur
        - *catOne
        - *catPres
        - *catMed
        - *catIn
        - *catFinan
        - *catTax
        - *catEndow
        - *catBig
        - *catInvest
        - *catAcc

moneyReservoirs:
    - &reservoirCashCommon
        code: CASH_COMMON
        name: Cash Common
        owner: *accountCommon
    - &reservoirCardCommon
        code: CARD_COMMON
        name: Card Common (£)
        owner: *accountCommon
        currency: GBP
    - &reservoirCardBob
        code: CARD_BOB
        name: Card Bob
        owner: *accountBob
    - &reservoirCashAlice
        code: CASH_ALICE
        name: Cash Alice (£)
        owner: *accountAlice
        currency: GBP
    - &reservoirCardAlice
        code: CARD_ALICE
        name: Card Alice
        owner: *accountAlice
    - &reservoirSavingsAlice
        code: SAVINGS_ALICE
        name: Savings account Alice at Just-Another-Bank
        shorterName: Savings Alice
        owner: *accountAlice
        hidden: true

templates:
  - code: new-withdrawal
    name: New Withdrawal
    placement: [CASH_FLOW_VIEW]
    zeroSum: true
    icon: fa fa-credit-card fa-fw
    transactions:
      - beneficiaryCode: ${account.code}
        moneyReservoirCode: ${account.defaultElectronicReservoir.code}
        categoryCode: ACC
        description: Withdrawal
        flowAsFloat: -50
      - beneficiaryCode: ${account.code}
        moneyReservoirCode: ${account.defaultCashReservoir.code}
        categoryCode: ACC
        description: Withdrawal
        flowAsFloat: 50
  - code: new-endowment
    name: New Endowment
    placement: [ENDOWMENTS_VIEW]
    zeroSum: true
    icon: icon-crown
    transactions:
      - beneficiaryCode: Common
        moneyReservoirCode: "" # N/A
        categoryCode: ENDOW
        description: Endowment for ${account.longName}
      - beneficiaryCode: ${account.code}
        moneyReservoirCode: "" # N/A
        categoryCode: ENDOW
        description: Endowment for ${account.longName}

  - code: bakery
    name: Bakery
    placement: [TEMPLATE_LIST]
    icon: icon-food
    transactions:
      - beneficiaryCode: Common
        moneyReservoirCode: ${account.defaultCashReservoir.code}
        categoryCode: LIFE
        description: Bakery
        flowAsFloat: -2.1
  - code: wages-alice
    name: Wages Alice
    placement: [TEMPLATE_LIST]
    icon: fa fa-suitcase fa-fw
    onlyShowForUserLoginNames: [alice]
    transactions:
      - beneficiaryCode: Alice
        moneyReservoirCode: CARD_ALICE
        categoryCode: IN
        description: Wages
        flowAsFloat: 910
  - code: wages-bob
    name: Wages Bob
    placement: [TEMPLATE_LIST]
    icon: fa fa-suitcase fa-fw
    onlyShowForUserLoginNames: [bob]
    transactions:
      - beneficiaryCode: Bob
        moneyReservoirCode: CARD_BOB
        categoryCode: IN
        description: Wages
        flowAsFloat: 900

constants:
  commonAccount: *accountCommon
  accountingCategory: *catAcc
  endowmentCategory: *catEndow
  liquidationDescription: Liquidation
