name: Docker Image Release

on:
  release:
    types: [published]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Create directory for release assets
        run: mkdir -p release-assets
#
#      - name: Extract version from tag
#        id: get_version
#        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download release asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download "$GITHUB_REF_NAME" \
            -p "release-${{ github.ref_name }}.tar.gz" \
            -D release-assets

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          build-args: |
            ASSET_FILENAME=release-${{ github.ref_name }}.tar.gz
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/facto:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/facto:latest
